### ISSUE TITLE
刚开档不久，补助环节补助名称和介绍出现错误

### ISSUE THREAD

**Issue by JerryM0623** [yuanze31/All-in-One-Deluxe#1]
问题：单条补助的名称和介绍文本变成了英文（可能是变量名？）
出现情形：开新档，完成一个补助（补助内容就是建造办公室开启财政线路），技能点开启了财政和安保支线
bug截图：
![image](https://user-images.githubusercontent.com/43034558/205448035-22e4cb49-cb8e-456d-b9ec-4f2bc78ab278.png)
![image](https://user-images.githubusercontent.com/43034558/205448047-310a9fd2-560a-41fb-9adb-b4f665f38dd9.png)

**Comment by yuanze31** [comment]
这个是目前翻译文件没有迁移完全导致的
也是我最近正在做的事情

**Comment by JerryM0623** [comment]
好的好的
